
- name: templates out node csr
  become: yes
  template:
    src: node-csr.json.j2
    dest: "/usr/share/ca-certificates/kthw/{{ node }}-csr.json"

- name: generate node and node key pems
  become: yes
  shell: |-
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -hostname={{ node }},{{ hostvars[node].ip }} -profile=kubernetes {{ node }}-csr.json | cfssljson -bare {{ node }}
    chmod 0644 {{ node }}-key.pem
  args:
    chdir: /usr/share/ca-certificates/kthw

- name: copy pems and pems key to nodes
  delegate_to: "{{ node }}"
  become: yes
  copy:
    src: "/usr/share/ca-certificates/kthw/{{ pem.file }}"
    dest: /root
    mode: "{{ pem.mode }}"
  loop:
    - file: ca.pem
      mode: 644
    - file: "{{ node }}.pem"
      mode: 644
    - file: "{{ node }}-key.pem"
      mode: 600
  loop_control:
    loop_var: pem
